---
title: "Práctica 10. Ensamblaje de genomas"
author: "Luis Pérez Lucena"
format: html
engine: knitr
---

## Objetivo

Ensamblar el genoma de un eucariota diploide con lecturas de PacBio de alta fidelidad.

## Preparación

# Hifiasm

El programa hifiasm no está instalado en los ordenadores virtuales, y por tanto es necesario hacerlo manualmente, siguiendo los pasos siguientes en el terminal de Bash. Lo recomendable es instalarlo en una carpeta bin dentro de la carpeta de usuaria.

```{bash}
if [ ! -d ~/bin ]; then mkdir ~/bin; fi
cd ~/bin
git clone https://github.com/chhylp123/hifiasm
cd hifiasm
make
```

Una vez compilado, el ejecutable \~/bin/hifiasm/hifiasm estará disponible, pero no en el PATH (donde Bash pueda encontrarlo). Para que hifiasm esté en el PATH, podemos añadir la carpeta \~/bin/hifiasm al PATH. En el terminal de Bash esto se consigue con la orden export PATH=\$PATH:\~/bin/hifiasm. Pero esta orden sólo afecta el terminal en el que se ha ejecutado. Para modificar el PATH permanentemente hay que incluir esta orden en el script \~/.bashrc. Puedes hacerlo automáticamente con la orden siguiente, pero asegúrte de ejecutarla sólo una vez:

```{bash}
echo 'export PATH=$PATH:~/bin/hifiasm' >> ~/.bashrc
```

A partir de entonces, cada vez que inicies el terminal, hifiasm estará en el PATH. Pero el terminal desde el cual has ejecutado la orden anterior se abrió antes de modificar .bashrc. Para que surta efecto sin tener que cerrar y abrir el terminal, puedes usar la orden . \~/.bashrc.

Hace falta instalar también otro programa, pero empecemos primero la práctica y más adelante.

## Datos

Vamos a usar lecturas HiFi generadas por Rabanal et al. (2022) de un único individuo de la planta Arabidopsis thaliana, ecotipo Columbia (Col-0), con la tecnología SMRT de PacBio (proyecto PRJEB50694). Los datos seleccionados son solo una parte de los originales y se encuentran en el archivo At4.10.fa.gz (46 Mb), disponible en el aula virtual. También está en el espacio de disco compartido de la Universidad de Valencia, dentro del grupo de bioinformática. Este espacio es directamente accesible desde los ordenadores virtuales.

En adelante supondré que el archivo está guardado en la carpeta data y que su path relativo es ../../data/At4.10.fa.gz.

## Resolución de datos

Los datos están en formato FASTA porque contienen sólo lecturas de alta calidad, y hifiasm no utiliza la información de las calidades de cada base. El archivo está comprimido. Antes de empezar el ensamblaje deberíamos tener una idea de la cantidad de datos que tenemos. Si lo necesitas, utiliza una inteligencia artificial para responder las preguntas siguientes y anota en un bloque de código las órdenes utilizadas. Puedes hacerlo con instrucciones de Bash o de R, pero R necesitará cargar en memoria el archivo entero, lo que no sería muy práctico si se tratara de un archivo 10 o 50 veces mayor.

**Ejercicio 1** - ¿Cuántas secuencias contiene el archivo? Como tenemos el archivo en formato FASTA, sabemos que lo más normal es que las líneas empiecen por "\>". Por ello, utilizamos la función "zgrep" (el archivo está commprimido) para preguntarle cuantas líneas empiezan por dicho caracter, de la siguiente manera:

```{bash}
zgrep -c ">" ../../Data/At4.10.fa.gz
```

Asumiendo que todas las secuencias empiezan por este caracter. concluimos que este archivo contiene 13812 secuencias.

-   ¿Qué longitudes mínima, media y máxima tienen las secuencias?

```{bash}
zcat ../../Data/At4.10.fa.gz | awk '!/^>/ {len=length($0); sum+=len; if(min==""){min=max=len}; if(len<min) min=len; if(len>max) max=len; count++} END {print "Mínima:", min, "Media:", sum/count, "Máxima:", max}'
```

La explicación del comando sería la siguiente:

!/\^\>/: Selecciona solo la línea de la secuencia (la que comienza por el símbolo "\>", son las líneas de las secuencias en el formato FASTA).

length(\$0): Calcula la longitud de esa línea.

sum/count: Calcula el promedio al final (END).

min/max: Actualiza los valores mínimo y máximo según recorre el archivo.

-   ¿Cuál es el número total de bases?

```{bash}
zcat ../../Data/At4.10.fa.gz | awk '!/^>/ {sum += length($0)} END {print sum}'
```

La explicación del comando empleado es:

!/\^\>/: Le dice al terminal: "coge las líneas que empiecen por \>". Esto es perfecto porque en el formato FASTQ, las líneas de las secuencias comienzan por dicho símbolo.

sum += length(\$0): Va acumulando la longitud de cada línea en una variable llamada sum.

END {print sum}: Una vez que termina de leer todo el archivo, imprime el resultado final.

Zcat vuelve a contar los caracteres en las líneas que empiezan por "\>". Sum += length(\$0) va sumando acumulativamente todos los caracteres de esas líneas y lo introduce en la variable sum, al final mostrándolo con la función print.

-   Si se estimara que el genoma a ensamblar fuera de sólo 19 millones de bases, ¿cuál sería la cobertura esperada?

Para determinar la cobertura, simplemente tendríamos que dividir el número total de bases (el resultado de nuestro tercer apartado) entre el tamaño teórico de nuestro genoma (19000000). El resultado es de 13.18945, por lo que la cobertura esperada será de aproximadamente 13. En término medio puede estar bien, pero el problema con la cobertura es que fluctúa de forma muy brusca, de forma que puede que haya regiones que hayan sido secuenciadas más de 20 veces y otras que absolutamente nada. Por ello, interesa que la cobertura sea algo más generosa, en torno a 30.

En nuestro caso, estamos trabajando con la secuenciación de un genoma diploide. Con esta cobertura, puede que haya regiones de las que solo hayamos secuenciado una de las copias, lo cual puede resutar problemático dependiendo del objetivo de dicha secuenciación.

En general, en todo el ejercicio hemos usado la función "awk", que es un motor que recorre los archivos línea por línea, permitiéndote "hacer preguntas" o realizar cálculos sobre los datos que contienen.

## Ensamblaje

El programa hifiasm produce varios archivos de salida. Para tener la carpeta de trabajo ordenada, es recomendable crear un subcarpeta donde poder guardarlos. Si fuéramos a probar más de una estrategia de ensamblado, guardaríamos los resultados de cada intento en una carpeta diferente, que podríamos nombrar asm1, asm2, etc. Aunque sólo realicemos un ensamblaje, crearemos la carpeta asm1 para guardar los resultados en ella.

```{bash}
# Con la ejecución condicional nos ahorramos algún mensaje de error:
if [ ! -d asm1 ]; then mkdir asm1; fi
```

El ensamblaje de estas lecturas puede durar unos minutos. No queremos tener que ejecutarlo cada vez que compilamos el documento de Quarto. Tenemos dos opciones: o bien usamos la directriz #\| cache: true al principio del bloque de código o bien controlamos directamente la ejecución condicional con Bash. Si usamos el método que ofrece Quarto, aparecerá una nueva carpeta que guarda resultados previos y que estaría bien incluir en el repositorio de Git. Yo prefiero usar Bash:

```{bash}
#| cache: true
export PATH=$PATH:~/bin/hifiasm
if [ ! -e asm1/At4.bp.p_ctg.gfa ]; then
   hifiasm -o asm1/At4 -t 2 -f 0 ../../Data/At4.10.fa.gz 2> asm1/hifiasm.log
   # La ! niega lo que viene a continuación, mientras que el -e significa "existe"
fi
```

Las opciones significan lo siguiente:

-   o asm1/At4: usa el prefijo asm1/At4 para los archivos de salida.
-   t 2: usa dos procesadores. Por defecto usaría uno.
-   f 0: inhabilita el uso de un filtro de Bloom (Melsted and Pritchard 2011) durante la corrección de errores, que ocuparía 16 Gb de memoria.
-   ../../data/At4.10.fa.gz: archivo con los datos de partida.
-   2\> asm1/hifiasm.log: guarda los numerosos mensajes que hifiasm envía al error estándar en un archivo asm1/hifiasm.log. Esto evita que esos mensajes se acumulen en el informe HTML.

**Ejercicio 2** Consulta la ayuda de hifiasm (hifiasm -h) y contesta las preguntas siguientes:

¿Los parámetros corresponden al ensamblaje de un genoma haploide o diploide? Gracias a la ayuda de hifiasm, sabemos que para saber el número de haplotipos del genoma secuenciado, tenemos que hacer uso de la opción "--n-hap". Por defecto, en caso de que le digamos lo contrario, el programa considera que se trata de un genoma diploide.

¿Qué nivel de eliminación de duplicaciones hemos aplicado? (El paso de eliminar duplicaciones sirve para que las zonas de alta heterocigosidad no sean ensambladas como contigs diferentes). Para conocer este parámetro, tendríamos que utilizar la opción "-l" del programa. Por defecto, el programa nos aplica un nivel 3 "agresivo", dado que estamos usando un archivo tipo unzip.

Si tuvieramos lecturas ultra-largas, ¿con qué opción o argumento añadiríamos esa información? Para indicar qué archivos son los que corresponden a lecturas ultra-largas, usaríamos la opción "--ul FILEs".

## Evaluación del resultado

**Ejercicio 3** Consulta la descripción de los archivos de salida que encontrarás en este enlace y contesta las preguntas siguientes:

¿Dónde están las secuencias que componen el ensamblaje? Estarán en el archvio que cumpla estas características: `prefix`.r_utg.gfa: haplotype-resolved raw unitig graph. En nuestro caso, este archivo es el At4.bp.r_utg.gfa, que contendrá las secuencias sin procesar.

En los archivos .gfa, ¿qué son las líneas que empiezan por ‘A’? Hifiasm outputs A lines including the information of reads which are used to construct contig/unitig. Each A line is plain-text, tab-separated. Las líneas que comienzan por A contienen las lecturas que han sido empleadas para construir los contigs.

¿Qué información tiene los archivos .bed? The coordinates of low quality regions are written to \*lowQ.bed in BED format. Estos archivos contienen las coordenadas de las regiones en las que el ensamblaje es de baja calidad.

¿Cuál es la cobertura media estimada de las secuencias homocigotas? Para ver la cobertura media, tenemos que interpretar es gráfico "k-mer plot" dentro del archivo "hifiasm.log". La cobertura estimada de las secuencias homocigotas será la correspondiente a donde se sitúa el pico. En nuestro caso, la cobertura es en torno a 12. k-mer plot: showing how many k-mers appear a certain number of times. For homozygous samples, there should be one peak around read coverage.

¿Y la de las heterocigotas? Lo mismo, pero teniendo en cuenta que la cobertura de las heterocigotas estará en torno al primero de los picos. Sabiendo que la cobertura de las secuencias homocigotas, debería haber un primer pico más pequeño en 6, pero no lo hay. Seguramente el organismo sea homocigoto, se trata de una planta que puede haber sido autofecundada muchas veces y habrá alcanzado este estado. For heterozygous samples, there should be two peaks, where the smaller peak is around the heterozygous read coverage and the larger peak is around the homozygous read coverage

Los ensamblajes primario y por haplotipos se presentan en formato GFA. Para extraer las secuencias en formato FASTA podemos usar el pequeño script siguiente, en lenguaje AWK, desde el terminal de Bash:

```{bash}
#| cache: true
awk '(/^S/){print ">" $2 "\n" $3}' asm1/At4.bp.p_ctg.gfa > asm1/At4.fa
```

# Calidad del ensamblaje

Para obtener las estadísticas del ensamblaje utilizaremos el programa compleasm (Huang and Li 2023), que no está instalado en el ordenador virtual. Está programado en Python y depende del módulo pandas de Python. En WSL, este módulo o paquete probablemente pueda instalarse con apt install python3-pandas. Alternativamente, en los sistemas con conda podéis hacer conda install pandas. En el ordenador virtual, el módulo pandas ya está disponible.

```{bash}
cd ~/bin
wget https://github.com/huangnengCSU/compleasm/releases/download/v0.2.7/compleasm-0.2.7_x64-linux.tar.bz2
tar -jxvf compleasm-0.2.7_x64-linux.tar.bz2
```

En adelante supondré que compleasm.py está en \~/bin/compleasm_kit. El programa necesita descargar la lista de genes típica del linaje al que pertenece el ensamblaje. En nuestro caso, el linaje es el de las Brassicales. La orden siguiente puede tomar más de 10 minutos.

**Ejercicio 4** 
Consulta la ayuda de compleasm.py y averigua qué significan los argumentos utilizados.

# Visualización del grafo

Desafortunadamente, no existe todavía ningún paquete de R para visualizar ensamblajes como grafos de fragmentos a partir de archivos .gfa. Uno de los visualizadores más populares es bandage, una aplicación gráfica que puede instalarse fácilmente en cualquier sistema operativo, pero que no ofrece interfaz por línea de comandos.

**Ejercicio 5** Instala bandage, carga el grafo del ensamblaje realizado y genera una figura. Puedes añadir la figura al informe HTML mediante la sitaxis siguiente:


library(Biostrings)
asm1 <- readDNAStringSet('asm1/At4.fa')
asm1.len <- data.frame(
  len = sort(width(asm1),
             decreasing = TRUE)
)
asm1.len$cumlen <- cumsum(asm1.len$len)
asm1.len$cumprop <- asm1.len$cumlen / 
                    sum(asm1.len$len)
asm1.len

Ejecutando esto, podríamos saber las longitudes acumuladas.